# Generated by Django 5.0.4 on 2024-07-11 16:08

import main_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, validators=[main_app.validators.ValidateName('Name can only contain letters and spaces')]),
        ),
    ]
