# Generated by Django 5.0.4 on 2024-06-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
