# Generated by Django 5.0.4 on 2024-06-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_exercise_duration_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
    ]
