# Generated by Django 5.0.4 on 2024-07-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('elemental_power', models.CharField(max_length=100)),
                ('spellbook_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
